server:
  port: 8080 # Gateway Service runs on port 8080

spring:
  application:
    name: gateway-service
  config:
    import: "optional:consul:" # Import Consul configuration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable dynamic discovery-based routing
      routes:
        # Explicit route for Group Service
        - id: group-service
          uri: lb://group-service
          predicates:
            - Path=/group/**
        # Explicit route for User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        # Explicit route for Runescape Service
        - id: runescape-service
          uri: lb://runescape-service
          predicates:
            - Path=/runescape/**
        # Explicit route for Search Service
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
          # Explicit route for communication service
        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/communication/**


management:
  endpoints:
    web:
      exposure:
        include: "*"


