server:
  port: 8080 # Gateway Service runs on port 8080

spring:
  application:
    name: gateway-service
  config:
    import: "optional:consul:"
  cloud:
    consul:
      enabled: true
      discovery:
        prefer-ip-address: true
        query-passing: true
      config:
        data-key: application.yml
        prefixes: config
        format: yaml
        default-context: defaults
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/user/**]': # Apply CORS to user-service routes
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
          '[/runescape/**]': # Apply CORS to runescape-service routes
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
          '[/search/**]': # Apply CORS to search-service routes
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
          '[/livesearch/**]': # Apply CORS to livesearch-service routes
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
          '[/livesearch2/**]': # Apply CORS to livesearch-service2 routes
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true

          '[/friend/**]': # Apply CORS to friend-service routes
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
          '[/profile/**]': # Apply CORS to profile-service routes
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
          '[/leaderboard/**]': # Apply CORS to leaderboard-service routes
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
          '[/group/**]': # Apply CORS to leaderboard-service routes
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: group-service
          uri: lb://group-service
          predicates:
            - Path=/group/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: runescape-service
          uri: lb://runescape-service
          predicates:
            - Path=/runescape/**
          filters:
            - StripPrefix=1

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1

        - id: livesearch-service
          uri: lb://livesearch-service
          predicates:
            - Path=/livesearch/**
          filters:
            - StripPrefix=1

        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/communication/**
          filters:
            - StripPrefix=1

        - id: friend-service
          uri: lb://friend-service
          predicates:
            - Path=/friend/**
          filters:
            - StripPrefix=1

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
          filters:
            - StripPrefix=1

        - id: leaderboard-service
          uri: lb://leaderboard-service
          predicates:
            - Path=/leaderboard/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
