version: "3.8"

services:
  # Communication Service
  playpal-communication-service:
    container_name: playpal-communication-service-container
    image: playpal-communication-service:latest
    ports:
      - "3002:3002"
    networks:
      - playpal-network


  # Friend Service
  playpal-friend-service:
    container_name: playpal-friend-service-container
    image: playpal-friend-service:latest
    ports:
      - "3003:3003"
    networks:
      - playpal-network

  # Frontend Service
  playpal-frontend:
      container_name: playpal-frontend-container
      image: playpal-frontend:latest
      ports:
        - "80:80"
      networks:
        - playpal-network

networks:
  playpal-network:
    driver: bridge

