version: "3.8"

services:

  # Communication Service
  playpal-communication-service:
    container_name: playpal-communication-service-container
    build:
      context: ../playpal-communication-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - playpal-network

  # Friend Service
  playpal-friend-service:
    container_name: playpal-friend-service-container
    build:
      context: ../playpal-friend-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    networks:
      - playpal-network

  # Frontend Service
  playpal-frontend:
    container_name: playpal-frontend-container
    build:
      context: ../playpal-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - playpal-network

  # Gateway
  playpal-gateway:
    container_name: playpal-gateway-container
    build:
      context: ../playpal-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - playpal-network

  # Group Service
  playpal-group-service:
    container_name: playpal-group-service-container
    build:
      context: ../playpal-group-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - playpal-network

  # Profile Service
  playpal-profile-service:
    container_name: playpal-profile-service-container
    build:
      context: ../Playpal-profile-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    networks:
      - playpal-network

  # Recorder
  playpal-recorder:
    container_name: playpal-recorder-container
    build:
      context: ../playpal-recorder
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - playpal-network


  # Runescape Service
  playpal-runescape-service:
    container_name: playpal-runescape-service-container
    build:
      context: ../playpal-runescape-service
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    networks:
      - playpal-network

  # User Service
  playpal-user-service:
    container_name: playpal-user-service-container
    build:
      context: ../playpal-user-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - playpal-network


networks:
  playpal-network:
    driver: bridge