version: '3.8'

services:


  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    networks:
      - playpal-network
    ports:
      - "9090:8080"
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  # Consul Service
  consul:
    image: hashicorp/consul:1.19.2
    container_name: consul-container
    ports:
      - "8500:8500"
    networks:
      - playpal-network
    command: "agent -dev -client=0.0.0.0"
    labels:
      - dev.dozzle.group=Configs

  # Consul Importer Service
  consul-importer:
    image: consul-importer:1.19.2
    container_name: consul-importer-container
    depends_on:
      - consul
    networks:
      - playpal-network
    labels:
      - dev.dozzle.group=Configs

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management console
    networks:
      - playpal-network
    labels:
      - dev.dozzle.group=Configs


  # Profile Service
  profile-service:
    container_name: profile
    image: profile-service:1.0
    ports:
      - "3001:3001"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
      - user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=myapp

  # Communication Service
  communication-service:
    container_name: communication
    image: communication-service:1.0
    ports:
      - "3002:3002"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=myapp

  # Friend Service
  friend-service:
    container_name: friend
    image: friend-service:1.0
    ports:
      - "3003:3003"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=myapp

  # Group Service
  group-service:
    container_name: group
    image: group-service:1.0
    ports:
      - "3005:3005"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=myapp

  # Leaderboard service
  leaderboard-service:
    container_name: leaderboard
    image: leaderboard-service:1.0
    ports:
      - "3012:3012"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=EndlessFetch

  # Runescape Service
  runescape-service:
    container_name: runescape
    image: runescape-service:1.0
    ports:
      - "3006:3006"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=myapp

  # Search Service
  search-service:
    container_name: search
    image: search-service:1.0
    ports:
      - "3007:3007"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=myapp

  # Livesearch Service
  livesearch-service:
    container_name: livesearch
    image: livesearch-service:1.0
    ports:
      - "3040:3040"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=myapp

  # User Service
  user-service:
    container_name: user
    image: user-service:1.0
    ports:
      - "3008:3008"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=myapp

  # Gateway Service
  gateway:
    container_name: gateway
    image: gateway:1.0
    ports:
      - "8080:8080"
    networks:
      - playpal-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    labels:
      - dev.dozzle.group=myapp

  # Frontend Service
  frontend:
    container_name: frontend-container
    image: frontend:1.0
    ports:
      - "3000:80"
    networks:
      - playpal-network
    working_dir: /app


networks:
  playpal-network:
    driver: bridge
